// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use crate::api::ContinuousJoinerExt;
use crate::api::JoinedExt;
use crate::api::SplitExt;
use bbqr::continuous_join::*;
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = DcoCodec,
    default_rust_opaque = RustOpaqueNom,
    default_rust_auto_opaque = RustAutoOpaqueNom,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.9.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 85803071;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__bbqr__continuous_join__ContinuousJoiner_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ContinuousJoiner_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::continuous_join::ContinuousJoiner::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<
        RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>,
    >,
    part: impl CstDecode<String>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ContinuousJoiner_frb_override_add_part(dart_style=add_part)",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            let api_part = part.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let mut api_that_guard = None;
                    let decode_indices_ =
                        flutter_rust_bridge::for_generated::lockable_compute_decode_order(vec![
                            flutter_rust_bridge::for_generated::LockableOrderInfo::new(
                                &api_that, 0, true,
                            ),
                        ]);
                    for i in decode_indices_ {
                        match i {
                            0 => api_that_guard = Some(api_that.lockable_decode_sync_ref_mut()),
                            _ => unreachable!(),
                        }
                    }
                    let mut api_that_guard = api_that_guard.unwrap();
                    let output_ok = bbqr::continuous_join::ContinuousJoiner::frb_override_add_part(
                        &mut *api_that_guard,
                        api_part,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__continuous_join__ContinuousJoiner_new_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ContinuousJoiner_new",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::continuous_join::ContinuousJoiner::new())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__encode__encoding_as_byte_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<bbqr::encode::Encoding>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encoding_as_byte",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::encode::Encoding::as_byte(&api_that))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__encode__encoding_from_byte_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    byte: impl CstDecode<u8>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encoding_from_byte",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_byte = byte.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::encode::Encoding::from_byte(api_byte))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__encode__encoding_is_known_encoding_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    byte: impl CstDecode<u8>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encoding_is_known_encoding",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_byte = byte.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::encode::Encoding::is_known_encoding(api_byte))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__encode__encoding_split_mod_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<bbqr::encode::Encoding>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "encoding_split_mod",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::encode::Encoding::split_mod(&api_that))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__file_type__file_type_as_byte_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<bbqr::file_type::FileType>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "file_type_as_byte",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::file_type::FileType::as_byte(&api_that))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__file_type__file_type_from_byte_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    byte: impl CstDecode<u8>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "file_type_from_byte",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_byte = byte.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::file_type::FileType::from_byte(api_byte))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__file_type__file_type_is_known_filetype_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    byte: impl CstDecode<u8>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "file_type_is_known_filetype",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_byte = byte.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        bbqr::file_type::FileType::is_known_filetype(api_byte),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__join__joined_frb_override_try_from_parts_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    parts: impl CstDecode<Vec<String>>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "joined_frb_override_try_from_parts(dart_style=try_from_parts)",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_parts = parts.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = bbqr::join::Joined::frb_override_try_from_parts(api_parts)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__split__split_frb_override_try_from_data_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    bytes: impl CstDecode<Vec<u8>>,
    file_type: impl CstDecode<bbqr::file_type::FileType>,
    options: impl CstDecode<bbqr::split::SplitOptions>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "split_frb_override_try_from_data(dart_style=try_from_data)",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_bytes = bytes.cst_decode();
            let api_file_type = file_type.cst_decode();
            let api_options = options.cst_decode();
            move |context| {
                transform_result_dco::<_, _, String>((move || {
                    let output_ok = bbqr::split::Split::frb_override_try_from_data(
                        &api_bytes,
                        api_file_type,
                        api_options,
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__split__split_options_default_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "split_options_default",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(bbqr::split::SplitOptions::default())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__bbqr__qr__version_data_capacity_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    that: impl CstDecode<bbqr::qr::Version>,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::DcoCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "version_data_capacity",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let api_that = that.cst_decode();
            move |context| {
                transform_result_dco::<_, _, ()>((move || {
                    let output_ok =
                        Result::<_, ()>::Ok(bbqr::qr::Version::data_capacity(&api_that))?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: static_checks

#[allow(clippy::unnecessary_literal_unwrap)]
const _: fn() = || {
    {
        let Joined = None::<bbqr::join::Joined>.unwrap();
        let _: bbqr::encode::Encoding = Joined.encoding;
        let _: bbqr::file_type::FileType = Joined.file_type;
        let _: Vec<u8> = Joined.data;
    }
    {
        let Split = None::<bbqr::split::Split>.unwrap();
        let _: bbqr::qr::Version = Split.version;
        let _: Vec<String> = Split.parts;
        let _: bbqr::encode::Encoding = Split.encoding;
    }
    {
        let SplitOptions = None::<bbqr::split::SplitOptions>.unwrap();
        let _: bbqr::encode::Encoding = SplitOptions.encoding;
        let _: usize = SplitOptions.min_split_number;
        let _: usize = SplitOptions.max_split_number;
        let _: bbqr::qr::Version = SplitOptions.min_version;
        let _: bbqr::qr::Version = SplitOptions.max_version;
    }
};

// Section: dart2rust

impl CstDecode<bool> for bool {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bool {
        self
    }
}
impl CstDecode<bbqr::encode::Encoding> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bbqr::encode::Encoding {
        match self {
            0 => bbqr::encode::Encoding::Hex,
            1 => bbqr::encode::Encoding::Base32,
            2 => bbqr::encode::Encoding::Zlib,
            _ => unreachable!("Invalid variant for Encoding: {}", self),
        }
    }
}
impl CstDecode<bbqr::file_type::FileType> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bbqr::file_type::FileType {
        match self {
            0 => bbqr::file_type::FileType::Psbt,
            1 => bbqr::file_type::FileType::Transaction,
            2 => bbqr::file_type::FileType::Json,
            3 => bbqr::file_type::FileType::Cbor,
            4 => bbqr::file_type::FileType::UnicodeText,
            _ => unreachable!("Invalid variant for FileType: {}", self),
        }
    }
}
impl CstDecode<i32> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> i32 {
        self
    }
}
impl CstDecode<u8> for u8 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> u8 {
        self
    }
}
impl CstDecode<usize> for usize {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> usize {
        self
    }
}
impl CstDecode<bbqr::qr::Version> for i32 {
    // Codec=Cst (C-struct based), see doc to use other codecs
    fn cst_decode(self) -> bbqr::qr::Version {
        match self {
            0 => bbqr::qr::Version::V01,
            1 => bbqr::qr::Version::V02,
            2 => bbqr::qr::Version::V03,
            3 => bbqr::qr::Version::V04,
            4 => bbqr::qr::Version::V05,
            5 => bbqr::qr::Version::V06,
            6 => bbqr::qr::Version::V07,
            7 => bbqr::qr::Version::V08,
            8 => bbqr::qr::Version::V09,
            9 => bbqr::qr::Version::V10,
            10 => bbqr::qr::Version::V11,
            11 => bbqr::qr::Version::V12,
            12 => bbqr::qr::Version::V13,
            13 => bbqr::qr::Version::V14,
            14 => bbqr::qr::Version::V15,
            15 => bbqr::qr::Version::V16,
            16 => bbqr::qr::Version::V17,
            17 => bbqr::qr::Version::V18,
            18 => bbqr::qr::Version::V19,
            19 => bbqr::qr::Version::V20,
            20 => bbqr::qr::Version::V21,
            21 => bbqr::qr::Version::V22,
            22 => bbqr::qr::Version::V23,
            23 => bbqr::qr::Version::V24,
            24 => bbqr::qr::Version::V25,
            25 => bbqr::qr::Version::V26,
            26 => bbqr::qr::Version::V27,
            27 => bbqr::qr::Version::V28,
            28 => bbqr::qr::Version::V29,
            29 => bbqr::qr::Version::V30,
            30 => bbqr::qr::Version::V31,
            31 => bbqr::qr::Version::V32,
            32 => bbqr::qr::Version::V33,
            33 => bbqr::qr::Version::V34,
            34 => bbqr::qr::Version::V35,
            35 => bbqr::qr::Version::V36,
            36 => bbqr::qr::Version::V37,
            37 => bbqr::qr::Version::V38,
            38 => bbqr::qr::Version::V39,
            39 => bbqr::qr::Version::V40,
            _ => unreachable!("Invalid variant for Version: {}", self),
        }
    }
}
impl SseDecode for ContinuousJoinResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode for ContinuousJoiner {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { decode_rust_opaque_nom(inner) };
    }
}

impl SseDecode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return unsafe { decode_rust_opaque_nom(inner) };
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for bbqr::encode::Encoding {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => bbqr::encode::Encoding::Hex,
            1 => bbqr::encode::Encoding::Base32,
            2 => bbqr::encode::Encoding::Zlib,
            _ => unreachable!("Invalid variant for Encoding: {}", inner),
        };
    }
}

impl SseDecode for bbqr::file_type::FileType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => bbqr::file_type::FileType::Psbt,
            1 => bbqr::file_type::FileType::Transaction,
            2 => bbqr::file_type::FileType::Json,
            3 => bbqr::file_type::FileType::Cbor,
            4 => bbqr::file_type::FileType::UnicodeText,
            _ => unreachable!("Invalid variant for FileType: {}", inner),
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bbqr::join::Joined {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_encoding = <bbqr::encode::Encoding>::sse_decode(deserializer);
        let mut var_fileType = <bbqr::file_type::FileType>::sse_decode(deserializer);
        let mut var_data = <Vec<u8>>::sse_decode(deserializer);
        return bbqr::join::Joined {
            encoding: var_encoding,
            file_type: var_fileType,
            data: var_data,
        };
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<bbqr::encode::Encoding> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<bbqr::encode::Encoding>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<bbqr::file_type::FileType> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<bbqr::file_type::FileType>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for bbqr::split::Split {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_version = <bbqr::qr::Version>::sse_decode(deserializer);
        let mut var_parts = <Vec<String>>::sse_decode(deserializer);
        let mut var_encoding = <bbqr::encode::Encoding>::sse_decode(deserializer);
        return bbqr::split::Split {
            version: var_version,
            parts: var_parts,
            encoding: var_encoding,
        };
    }
}

impl SseDecode for bbqr::split::SplitOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_encoding = <bbqr::encode::Encoding>::sse_decode(deserializer);
        let mut var_minSplitNumber = <usize>::sse_decode(deserializer);
        let mut var_maxSplitNumber = <usize>::sse_decode(deserializer);
        let mut var_minVersion = <bbqr::qr::Version>::sse_decode(deserializer);
        let mut var_maxVersion = <bbqr::qr::Version>::sse_decode(deserializer);
        return bbqr::split::SplitOptions {
            encoding: var_encoding,
            min_split_number: var_minSplitNumber,
            max_split_number: var_maxSplitNumber,
            min_version: var_minVersion,
            max_version: var_maxVersion,
        };
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for bbqr::qr::Version {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => bbqr::qr::Version::V01,
            1 => bbqr::qr::Version::V02,
            2 => bbqr::qr::Version::V03,
            3 => bbqr::qr::Version::V04,
            4 => bbqr::qr::Version::V05,
            5 => bbqr::qr::Version::V06,
            6 => bbqr::qr::Version::V07,
            7 => bbqr::qr::Version::V08,
            8 => bbqr::qr::Version::V09,
            9 => bbqr::qr::Version::V10,
            10 => bbqr::qr::Version::V11,
            11 => bbqr::qr::Version::V12,
            12 => bbqr::qr::Version::V13,
            13 => bbqr::qr::Version::V14,
            14 => bbqr::qr::Version::V15,
            15 => bbqr::qr::Version::V16,
            16 => bbqr::qr::Version::V17,
            17 => bbqr::qr::Version::V18,
            18 => bbqr::qr::Version::V19,
            19 => bbqr::qr::Version::V20,
            20 => bbqr::qr::Version::V21,
            21 => bbqr::qr::Version::V22,
            22 => bbqr::qr::Version::V23,
            23 => bbqr::qr::Version::V24,
            24 => bbqr::qr::Version::V25,
            25 => bbqr::qr::Version::V26,
            26 => bbqr::qr::Version::V27,
            27 => bbqr::qr::Version::V28,
            28 => bbqr::qr::Version::V29,
            29 => bbqr::qr::Version::V30,
            30 => bbqr::qr::Version::V31,
            31 => bbqr::qr::Version::V32,
            32 => bbqr::qr::Version::V33,
            33 => bbqr::qr::Version::V34,
            34 => bbqr::qr::Version::V35,
            35 => bbqr::qr::Version::V36,
            36 => bbqr::qr::Version::V37,
            37 => bbqr::qr::Version::V38,
            38 => bbqr::qr::Version::V39,
            39 => bbqr::qr::Version::V40,
            _ => unreachable!("Invalid variant for Version: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<ContinuousJoinResult> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<ContinuousJoinResult>
{
}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<ContinuousJoinResult>> for ContinuousJoinResult {
    fn into_into_dart(self) -> FrbWrapper<ContinuousJoinResult> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<ContinuousJoiner> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<ContinuousJoiner> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<ContinuousJoiner>> for ContinuousJoiner {
    fn into_into_dart(self) -> FrbWrapper<ContinuousJoiner> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<bbqr::encode::Encoding> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            bbqr::encode::Encoding::Hex => 0.into_dart(),
            bbqr::encode::Encoding::Base32 => 1.into_dart(),
            bbqr::encode::Encoding::Zlib => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<bbqr::encode::Encoding>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<bbqr::encode::Encoding>>
    for bbqr::encode::Encoding
{
    fn into_into_dart(self) -> FrbWrapper<bbqr::encode::Encoding> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<bbqr::file_type::FileType> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            bbqr::file_type::FileType::Psbt => 0.into_dart(),
            bbqr::file_type::FileType::Transaction => 1.into_dart(),
            bbqr::file_type::FileType::Json => 2.into_dart(),
            bbqr::file_type::FileType::Cbor => 3.into_dart(),
            bbqr::file_type::FileType::UnicodeText => 4.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<bbqr::file_type::FileType>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<bbqr::file_type::FileType>>
    for bbqr::file_type::FileType
{
    fn into_into_dart(self) -> FrbWrapper<bbqr::file_type::FileType> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<bbqr::join::Joined> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.encoding.into_into_dart().into_dart(),
            self.0.file_type.into_into_dart().into_dart(),
            self.0.data.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<bbqr::join::Joined>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<bbqr::join::Joined>> for bbqr::join::Joined {
    fn into_into_dart(self) -> FrbWrapper<bbqr::join::Joined> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<bbqr::split::Split> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.version.into_into_dart().into_dart(),
            self.0.parts.into_into_dart().into_dart(),
            self.0.encoding.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<bbqr::split::Split>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<bbqr::split::Split>> for bbqr::split::Split {
    fn into_into_dart(self) -> FrbWrapper<bbqr::split::Split> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<bbqr::split::SplitOptions> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.encoding.into_into_dart().into_dart(),
            self.0.min_split_number.into_into_dart().into_dart(),
            self.0.max_split_number.into_into_dart().into_dart(),
            self.0.min_version.into_into_dart().into_dart(),
            self.0.max_version.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<bbqr::split::SplitOptions>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<bbqr::split::SplitOptions>>
    for bbqr::split::SplitOptions
{
    fn into_into_dart(self) -> FrbWrapper<bbqr::split::SplitOptions> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<bbqr::qr::Version> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self.0 {
            bbqr::qr::Version::V01 => 0.into_dart(),
            bbqr::qr::Version::V02 => 1.into_dart(),
            bbqr::qr::Version::V03 => 2.into_dart(),
            bbqr::qr::Version::V04 => 3.into_dart(),
            bbqr::qr::Version::V05 => 4.into_dart(),
            bbqr::qr::Version::V06 => 5.into_dart(),
            bbqr::qr::Version::V07 => 6.into_dart(),
            bbqr::qr::Version::V08 => 7.into_dart(),
            bbqr::qr::Version::V09 => 8.into_dart(),
            bbqr::qr::Version::V10 => 9.into_dart(),
            bbqr::qr::Version::V11 => 10.into_dart(),
            bbqr::qr::Version::V12 => 11.into_dart(),
            bbqr::qr::Version::V13 => 12.into_dart(),
            bbqr::qr::Version::V14 => 13.into_dart(),
            bbqr::qr::Version::V15 => 14.into_dart(),
            bbqr::qr::Version::V16 => 15.into_dart(),
            bbqr::qr::Version::V17 => 16.into_dart(),
            bbqr::qr::Version::V18 => 17.into_dart(),
            bbqr::qr::Version::V19 => 18.into_dart(),
            bbqr::qr::Version::V20 => 19.into_dart(),
            bbqr::qr::Version::V21 => 20.into_dart(),
            bbqr::qr::Version::V22 => 21.into_dart(),
            bbqr::qr::Version::V23 => 22.into_dart(),
            bbqr::qr::Version::V24 => 23.into_dart(),
            bbqr::qr::Version::V25 => 24.into_dart(),
            bbqr::qr::Version::V26 => 25.into_dart(),
            bbqr::qr::Version::V27 => 26.into_dart(),
            bbqr::qr::Version::V28 => 27.into_dart(),
            bbqr::qr::Version::V29 => 28.into_dart(),
            bbqr::qr::Version::V30 => 29.into_dart(),
            bbqr::qr::Version::V31 => 30.into_dart(),
            bbqr::qr::Version::V32 => 31.into_dart(),
            bbqr::qr::Version::V33 => 32.into_dart(),
            bbqr::qr::Version::V34 => 33.into_dart(),
            bbqr::qr::Version::V35 => 34.into_dart(),
            bbqr::qr::Version::V36 => 35.into_dart(),
            bbqr::qr::Version::V37 => 36.into_dart(),
            bbqr::qr::Version::V38 => 37.into_dart(),
            bbqr::qr::Version::V39 => 38.into_dart(),
            bbqr::qr::Version::V40 => 39.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<bbqr::qr::Version> {}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<bbqr::qr::Version>> for bbqr::qr::Version {
    fn into_into_dart(self) -> FrbWrapper<bbqr::qr::Version> {
        self.into()
    }
}

impl SseEncode for ContinuousJoinResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>,
        >>::sse_encode(
            flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self),
            serializer,
        );
    }
}

impl SseEncode for ContinuousJoiner {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, StdArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode
    for RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for bbqr::encode::Encoding {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                bbqr::encode::Encoding::Hex => 0,
                bbqr::encode::Encoding::Base32 => 1,
                bbqr::encode::Encoding::Zlib => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for bbqr::file_type::FileType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                bbqr::file_type::FileType::Psbt => 0,
                bbqr::file_type::FileType::Transaction => 1,
                bbqr::file_type::FileType::Json => 2,
                bbqr::file_type::FileType::Cbor => 3,
                bbqr::file_type::FileType::UnicodeText => 4,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bbqr::join::Joined {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bbqr::encode::Encoding>::sse_encode(self.encoding, serializer);
        <bbqr::file_type::FileType>::sse_encode(self.file_type, serializer);
        <Vec<u8>>::sse_encode(self.data, serializer);
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<bbqr::encode::Encoding> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <bbqr::encode::Encoding>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<bbqr::file_type::FileType> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <bbqr::file_type::FileType>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for bbqr::split::Split {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bbqr::qr::Version>::sse_encode(self.version, serializer);
        <Vec<String>>::sse_encode(self.parts, serializer);
        <bbqr::encode::Encoding>::sse_encode(self.encoding, serializer);
    }
}

impl SseEncode for bbqr::split::SplitOptions {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bbqr::encode::Encoding>::sse_encode(self.encoding, serializer);
        <usize>::sse_encode(self.min_split_number, serializer);
        <usize>::sse_encode(self.max_split_number, serializer);
        <bbqr::qr::Version>::sse_encode(self.min_version, serializer);
        <bbqr::qr::Version>::sse_encode(self.max_version, serializer);
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for bbqr::qr::Version {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                bbqr::qr::Version::V01 => 0,
                bbqr::qr::Version::V02 => 1,
                bbqr::qr::Version::V03 => 2,
                bbqr::qr::Version::V04 => 3,
                bbqr::qr::Version::V05 => 4,
                bbqr::qr::Version::V06 => 5,
                bbqr::qr::Version::V07 => 6,
                bbqr::qr::Version::V08 => 7,
                bbqr::qr::Version::V09 => 8,
                bbqr::qr::Version::V10 => 9,
                bbqr::qr::Version::V11 => 10,
                bbqr::qr::Version::V12 => 11,
                bbqr::qr::Version::V13 => 12,
                bbqr::qr::Version::V14 => 13,
                bbqr::qr::Version::V15 => 14,
                bbqr::qr::Version::V16 => 15,
                bbqr::qr::Version::V17 => 16,
                bbqr::qr::Version::V18 => 17,
                bbqr::qr::Version::V19 => 18,
                bbqr::qr::Version::V20 => 19,
                bbqr::qr::Version::V21 => 20,
                bbqr::qr::Version::V22 => 21,
                bbqr::qr::Version::V23 => 22,
                bbqr::qr::Version::V24 => 23,
                bbqr::qr::Version::V25 => 24,
                bbqr::qr::Version::V26 => 25,
                bbqr::qr::Version::V27 => 26,
                bbqr::qr::Version::V28 => 27,
                bbqr::qr::Version::V29 => 28,
                bbqr::qr::Version::V30 => 29,
                bbqr::qr::Version::V31 => 30,
                bbqr::qr::Version::V32 => 31,
                bbqr::qr::Version::V33 => 32,
                bbqr::qr::Version::V34 => 33,
                bbqr::qr::Version::V35 => 34,
                bbqr::qr::Version::V36 => 35,
                bbqr::qr::Version::V37 => 36,
                bbqr::qr::Version::V38 => 37,
                bbqr::qr::Version::V39 => 38,
                bbqr::qr::Version::V40 => 39,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.9.0.

    // Section: imports

    use super::*;
    use crate::api::ContinuousJoinerExt;
    use crate::api::JoinedExt;
    use crate::api::SplitExt;
    use bbqr::continuous_join::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    // Section: dart2rust

    impl CstDecode<ContinuousJoinResult> for usize {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> ContinuousJoinResult {
            flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
                RustOpaqueNom<
                    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>,
                >,
            >::cst_decode(
                self
            ))
        }
    }
    impl CstDecode<ContinuousJoiner> for usize {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> ContinuousJoiner {
            flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(CstDecode::<
                RustOpaqueNom<
                    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>,
                >,
            >::cst_decode(
                self
            ))
        }
    }
    impl
        CstDecode<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>,
            >,
        > for usize
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> RustOpaqueNom<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>,
        > {
            unsafe { decode_rust_opaque_nom(self as _) }
        }
    }
    impl
        CstDecode<
            RustOpaqueNom<
                flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>,
            >,
        > for usize
    {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(
            self,
        ) -> RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>
        {
            unsafe { decode_rust_opaque_nom(self as _) }
        }
    }
    impl CstDecode<String> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> String {
            let vec: Vec<u8> = self.cst_decode();
            String::from_utf8(vec).unwrap()
        }
    }
    impl CstDecode<bbqr::encode::Encoding> for *mut i32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bbqr::encode::Encoding {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<bbqr::encode::Encoding>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<bbqr::file_type::FileType> for *mut i32 {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bbqr::file_type::FileType {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<bbqr::file_type::FileType>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<bbqr::split::SplitOptions> for *mut wire_cst_split_options {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bbqr::split::SplitOptions {
            let wrap = unsafe { flutter_rust_bridge::for_generated::box_from_leak_ptr(self) };
            CstDecode::<bbqr::split::SplitOptions>::cst_decode(*wrap).into()
        }
    }
    impl CstDecode<bbqr::join::Joined> for wire_cst_joined {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bbqr::join::Joined {
            bbqr::join::Joined {
                encoding: self.encoding.cst_decode(),
                file_type: self.file_type.cst_decode(),
                data: self.data.cst_decode(),
            }
        }
    }
    impl CstDecode<Vec<String>> for *mut wire_cst_list_String {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<String> {
            let vec = unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            };
            vec.into_iter().map(CstDecode::cst_decode).collect()
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_loose {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<Vec<u8>> for *mut wire_cst_list_prim_u_8_strict {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> Vec<u8> {
            unsafe {
                let wrap = flutter_rust_bridge::for_generated::box_from_leak_ptr(self);
                flutter_rust_bridge::for_generated::vec_from_leak_ptr(wrap.ptr, wrap.len)
            }
        }
    }
    impl CstDecode<bbqr::split::Split> for wire_cst_split {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bbqr::split::Split {
            bbqr::split::Split {
                version: self.version.cst_decode(),
                parts: self.parts.cst_decode(),
                encoding: self.encoding.cst_decode(),
            }
        }
    }
    impl CstDecode<bbqr::split::SplitOptions> for wire_cst_split_options {
        // Codec=Cst (C-struct based), see doc to use other codecs
        fn cst_decode(self) -> bbqr::split::SplitOptions {
            bbqr::split::SplitOptions {
                encoding: self.encoding.cst_decode(),
                min_split_number: self.min_split_number.cst_decode(),
                max_split_number: self.max_split_number.cst_decode(),
                min_version: self.min_version.cst_decode(),
                max_version: self.max_version.cst_decode(),
            }
        }
    }
    impl NewWithNullPtr for wire_cst_joined {
        fn new_with_null_ptr() -> Self {
            Self {
                encoding: Default::default(),
                file_type: Default::default(),
                data: core::ptr::null_mut(),
            }
        }
    }
    impl Default for wire_cst_joined {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_split {
        fn new_with_null_ptr() -> Self {
            Self {
                version: Default::default(),
                parts: core::ptr::null_mut(),
                encoding: Default::default(),
            }
        }
    }
    impl Default for wire_cst_split {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }
    impl NewWithNullPtr for wire_cst_split_options {
        fn new_with_null_ptr() -> Self {
            Self {
                encoding: Default::default(),
                min_split_number: Default::default(),
                max_split_number: Default::default(),
                min_version: Default::default(),
                max_version: Default::default(),
            }
        }
    }
    impl Default for wire_cst_split_options {
        fn default() -> Self {
            Self::new_with_null_ptr()
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__continuous_join__ContinuousJoiner_default(
        port_: i64,
    ) {
        wire__bbqr__continuous_join__ContinuousJoiner_default_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part(
        port_: i64,
        that: usize,
        part: *mut wire_cst_list_prim_u_8_strict,
    ) {
        wire__bbqr__continuous_join__ContinuousJoiner_frb_override_add_part_impl(port_, that, part)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__continuous_join__ContinuousJoiner_new(
        port_: i64,
    ) {
        wire__bbqr__continuous_join__ContinuousJoiner_new_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__encode__encoding_as_byte(port_: i64, that: i32) {
        wire__bbqr__encode__encoding_as_byte_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__encode__encoding_from_byte(
        port_: i64,
        byte: u8,
    ) {
        wire__bbqr__encode__encoding_from_byte_impl(port_, byte)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__encode__encoding_is_known_encoding(
        port_: i64,
        byte: u8,
    ) {
        wire__bbqr__encode__encoding_is_known_encoding_impl(port_, byte)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__encode__encoding_split_mod(
        port_: i64,
        that: i32,
    ) {
        wire__bbqr__encode__encoding_split_mod_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__file_type__file_type_as_byte(
        port_: i64,
        that: i32,
    ) {
        wire__bbqr__file_type__file_type_as_byte_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__file_type__file_type_from_byte(
        port_: i64,
        byte: u8,
    ) {
        wire__bbqr__file_type__file_type_from_byte_impl(port_, byte)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__file_type__file_type_is_known_filetype(
        port_: i64,
        byte: u8,
    ) {
        wire__bbqr__file_type__file_type_is_known_filetype_impl(port_, byte)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__join__joined_frb_override_try_from_parts(
        port_: i64,
        parts: *mut wire_cst_list_String,
    ) {
        wire__bbqr__join__joined_frb_override_try_from_parts_impl(port_, parts)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__split__split_frb_override_try_from_data(
        port_: i64,
        bytes: *mut wire_cst_list_prim_u_8_loose,
        file_type: i32,
        options: *mut wire_cst_split_options,
    ) {
        wire__bbqr__split__split_frb_override_try_from_data_impl(port_, bytes, file_type, options)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__split__split_options_default(port_: i64) {
        wire__bbqr__split__split_options_default_impl(port_)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_wire__bbqr__qr__version_data_capacity(
        port_: i64,
        that: i32,
    ) {
        wire__bbqr__qr__version_data_capacity_impl(port_, that)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>>::increment_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoinResult(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoinResult>>::decrement_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>::increment_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerContinuousJoiner(
        ptr: *const std::ffi::c_void,
    ) {
        unsafe {
            StdArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ContinuousJoiner>>::decrement_strong_count(ptr as _);
        }
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_cst_new_box_autoadd_encoding(value: i32) -> *mut i32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_cst_new_box_autoadd_file_type(value: i32) -> *mut i32 {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(value)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_cst_new_box_autoadd_split_options(
    ) -> *mut wire_cst_split_options {
        flutter_rust_bridge::for_generated::new_leak_box_ptr(
            wire_cst_split_options::new_with_null_ptr(),
        )
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_cst_new_list_String(len: i32) -> *mut wire_cst_list_String {
        let wrap = wire_cst_list_String {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(
                <*mut wire_cst_list_prim_u_8_strict>::new_with_null_ptr(),
                len,
            ),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(wrap)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_cst_new_list_prim_u_8_loose(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_loose {
        let ans = wire_cst_list_prim_u_8_loose {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_dart_bbqr_cst_new_list_prim_u_8_strict(
        len: i32,
    ) -> *mut wire_cst_list_prim_u_8_strict {
        let ans = wire_cst_list_prim_u_8_strict {
            ptr: flutter_rust_bridge::for_generated::new_leak_vec_ptr(Default::default(), len),
            len,
        };
        flutter_rust_bridge::for_generated::new_leak_box_ptr(ans)
    }

    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_joined {
        encoding: i32,
        file_type: i32,
        data: *mut wire_cst_list_prim_u_8_strict,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_String {
        ptr: *mut *mut wire_cst_list_prim_u_8_strict,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_loose {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_list_prim_u_8_strict {
        ptr: *mut u8,
        len: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_split {
        version: i32,
        parts: *mut wire_cst_list_String,
        encoding: i32,
    }
    #[repr(C)]
    #[derive(Clone, Copy)]
    pub struct wire_cst_split_options {
        encoding: i32,
        min_split_number: usize,
        max_split_number: usize,
        min_version: i32,
        max_version: i32,
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;
